debug: false

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/Users/arkovalchuk/data-dou/demo;AUTO_SERVER=TRUE
    username: sa
    password: password
  jpa:
    open-in-view: false
